#I __SOURCE_DIRECTORY__
#r "../../../packages/FsCheck/lib/net45/FsCheck.dll"
#r "../../../packages/FSPowerPack.Core.Community/Lib/Net40/FSharp.PowerPack.dll"
#r "../../../packages/FSPowerPack.Linq.Community/Lib/Net40/FSharp.PowerPack.Linq.dll"
#r "../../../packages/FSPowerPack.Metadata.Community/Lib/Net40/FSharp.PowerPack.Metadata.dll"
#r "../../../packages/FSPowerPack.Parallel.Seq.Community/Lib/Net40/FSharp.PowerPack.Parallel.Seq.dll"
#r "../../../packages/Newtonsoft.Json/lib/net45/Newtonsoft.Json.dll"
#r "../../../packages/NUnit/lib/net45/nunit.framework.dll"
#r "../../../packages/FsUnit/lib/net45/FsUnit.NUnit.dll"
#r "../../../packages/Fuchu/lib/Fuchu.dll"
#r "../../../packages/FsUnit/lib/net45/NHamcrest.dll"
#r "../../../packages/Suave/lib/net40/Suave.dll"
#r "../../../packages/Suave.Testing/lib/net40/Suave.Testing.dll"
#r "System.Core.dll"
#r "System.dll"
#r "System.Net.Http.dll"
#r "System.Numerics.dll"
#r "System.Runtime.Serialization.dll"
#r "System.Xml.dll"
#r "../../../packages/Unquote/lib/net45/Unquote.dll"

#r "../../../packages/Informedica.GenUtils.Lib/lib/net45/Informedica.GenUtils.Lib.dll"

#load "../../../paket-files/halcwb/YoLo/YoLo.fs"
      "../../../src/GenPDMS/AssemblyInfo.fs"
      "../../../src/GenPDMS/Utils.fs"
      "../../../src/GenPDMS/Json.fs"
      "../../../src/GenPDMS/Token.fs"
      "../../../src/GenPDMS/Request.fs"
      "../../../src/GenPDMS/User.fs"
      "../../../src/GenPDMS/Capability.fs"
      "../../../src/GenPDMS/Response.fs"
      "../../../src/GenPDMS/Mapping.fs"
      "../../../src/GenPDMS/Server.fs"
