// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#load "load-references-release.fsx"
#load "../../../paket-files/halcwb/YoLo/YoLo.fs"
      "../AssemblyInfo.fs"
      "../Utils.fs"
      "../Json.fs"
      "../Token.fs"
      "../Request.fs"
      "../User.fs"
      "../Capability.fs"
      "../Response.fs"
      "../Mapping.fs"
      "../Server.fs"
      "../Program.fs"
